language: rust
rust:
- stable
- beta
- nightly
sudo: false
install:
- wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.12.tar.gz
- tar xvfz libsodium-1.0.12.tar.gz
- cd libsodium-1.0.12
- ./configure && make && make install
- sudo ldconfig /usr/local/lib
script:
- cargo build --verbose
- cargo test --verbose
