[package]
authors = ["dnaq"]
description = "Fast cryptographic library for Rust (bindings to libsodium)"
documentation = "https://dnaq.github.io/sodiumoxide"
keywords = ["crypto", "NaCl", "libsodium"]
license = "MIT"
name = "sodiumoxide"
readme = "README.md"
repository = "https://github.com/dnaq/sodiumoxide"
version = "0.0.10"

[dependencies]
libc = "0.2"
libsodium-sys = "0.0.10"
serde = { version="0.7", optional = true }

[dev-dependencies]
serde = "0.7"
serde_json = "0.7"
hex = "0.2"

[features]
benchmarks = []
default = ["serde"]
