[package]
authors = ["dnaq"]
build = "build.rs"
description = "FFI binding to libsodium"
documentation = "https://sodiumoxide.github.io/sodiumoxide"
keywords = ["libsodium", "NaCl", "crypto"]
license = "MIT OR Apache-2.0"
links = "sodium"
name = "libsodium-sys"
repository = "https://github.com/sodiumoxide/sodiumoxide.git"
categories = ["cryptography", "api-bindings"]
version = "0.2.0"

[badges]
travis-ci = { repository = "sodiumoxide/sodiumoxide" }

[build-dependencies]
http_req = { version = "0.4", default-features = false, features = ["rust-tls"] }
sha2 = "0.8"
pkg-config = "0.3"



[target.'cfg(target_env = "msvc")'.build-dependencies]
libc = { version = "=0.2.48" , default-features = false }
vcpkg = "0.2"
zip = "0.5"

[target.'cfg(not(target_env = "msvc"))'.build-dependencies]
cc = "1.0"
libflate = "0.1"
tar = "0.4"

[dependencies]
libc = { version = "=0.2.48" , default-features = false }

[lib]
name = "libsodium_sys"

[features]
use-pkg-config = []
