[package]
authors = ["dnaq"]
build = "build.rs"
description = "FFI binding to libsodium"
documentation = "https://dnaq.github.io/sodiumoxide"
keywords = ["libsodium", "NaCl", "crypto"]
license = "MIT OR Apache-2.0"
links = "sodium"
name = "libsodium-sys"
repository = "https://github.com/dnaq/sodiumoxide.git"
categories = ["cryptography", "api-bindings"]
version = "0.0.16"

[badges]
travis-ci = { repository = "dnaq/sodiumoxide" }

[build-dependencies]
pkg-config = "0.3"

[target.'cfg(target_env = "msvc")'.build-dependencies]
vcpkg = "0.2"

[dependencies]
libc = "0.2"

[lib]
name = "libsodium_sys"
path = "lib.rs"
