[package]
authors = ["dnaq"]
build = "build.rs"
description = "FFI binding to libsodium"
documentation = "https://sodiumoxide.github.io/sodiumoxide"
keywords = ["libsodium", "NaCl", "crypto"]
license = "MIT OR Apache-2.0"
links = "sodium"
name = "libsodium-sys"
repository = "https://github.com/sodiumoxide/sodiumoxide.git"
categories = ["cryptography", "api-bindings"]
version = "0.1.0"

[badges]
travis-ci = { repository = "sodiumoxide/sodiumoxide" }

[build-dependencies]
pkg-config = "^0.3.11"
bindgen = "0.37.0"

[dependencies]
libc = { version = "^0.2.41" , default-features = false }

[lib]
name = "libsodium_sys"
