[package]
name = "libsodium-sys"
description = "FFI binding to libsodium"
repository = "https://github.com/dnaq/sodiumoxide.git"
keywords = ["libsodium", "NaCl", "crypto"]
version = "0.0.5"
authors = ["dnaq"]
links = "sodium"
build = "build.rs"
license = "MIT"

[lib]
name = "libsodium_sys"
path = "lib.rs"

[dependencies]
libc = "*"

[build-dependencies]
pkg-config = "*"
